# Generated by Django 6.0.6 on 2026-06-13 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0003_remove_product_image_url_productimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhiteList',
            new_name='Wishlist',
        ),
    ]
