# Generated by Django 6.0.6 on 2026-06-23 17:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0003_alter_cart_cart_id_alter_conversation_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
